name: clinvocdev
dependencies:
    - python=3.6.2
    - nose
    - unicodecsv
    - pandas
    - pip:
        - six
        - pyparsing==2.2.0
        - toolz==0.8.2
        - multipledispatch
        - terminaltables
